trigger:
- master

pool:
  name: 'Default' # Ensure this uses your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: true

- task: NuGetToolInstaller@1

- script: |
    dotnet build --configuration Release
    dotnet pack --configuration Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Package'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'mylatestfeed' # Update accordingly