trigger:
  - master

pool:
  name: Default  # Ensure your self-hosted agent is registered in this pool

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: false

- script: dotnet build --configuration Release
  displayName: 'Build Project'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '*/.csproj'  # Updated pattern to search recursively
    configurationToPack: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'  # Corrected pattern
    nuGetFeedType: 'internal'
    publishVstsFeed: 'ac8d670a-28e4-4b99-bfe7-f68a9a28381a/c954abfb-d093-4589-9507-9d35e310c053'  # Ensure this is correct
    allowPackageConflicts: true