trigger:
  - master

pool:
  name: Default  # Ensure you've set up your self-hosted agent

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: false

- script: dotnet build --configuration Release
  displayName: 'Build project'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '*/.csproj'
    configurationToPack: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'ac8d670a-28e4-4b99-bfe7-f68a9a28381a/c954abfb-d093-4589-9507-9d35e310c053'
        allowPackageConflicts: true